"""
Data contracts for the Edit Agent pipeline step.

EditInput  — bundles the three upstream outputs (AdAnalysis + PageStructure + PageAnalysis).
EditPlan   — structured edit plan returned by the LLM.
SectionEdit — one text replacement for one page section.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

from app.ad_agent.schemas import AdAnalysis
from app.page_agent.schemas import PageAnalysis, PageStructure


# ── Enums ──────────────────────────────────────────────────────────────────────


class EditType(str, Enum):
    """Type of edit being applied to a page section."""

    HEADLINE_REWRITE = "headline_rewrite"
    SUBHEADLINE_REWRITE = "subheadline_rewrite"
    CTA_UPDATE = "cta_update"
    BODY_REWRITE = "body_rewrite"
    TONE_ADJUSTMENT = "tone_adjustment"
    OFFER_INSERTION = "offer_insertion"
    TRUST_SIGNAL_ENHANCEMENT = "trust_signal_enhancement"


# ── Input ──────────────────────────────────────────────────────────────────────


class EditInput(BaseModel):
    """
    Composite input for the Edit Agent.

    Bundles the three upstream pipeline outputs into a single typed object.
    The orchestrator builds this from the results of Steps 1 and 2.
    """

    ad_analysis: AdAnalysis = Field(
        ...,
        description="Structured ad analysis from Step 1 (Ad Agent).",
    )
    page_structure: PageStructure = Field(
        ...,
        description="Scraped HTML and labeled sections from Step 2 (Page Agent).",
    )
    page_analysis: PageAnalysis = Field(
        ...,
        description="LLM quality assessment from Step 2 (Page Agent).",
    )


# ── Output — LLM-generated edit plan ──────────────────────────────────────────


class SectionEdit(BaseModel):
    """
    One text replacement for one page section.

    The ``section_id`` links back to ``PageSection.section_id`` so
    the Step 4 renderer can locate the element via its CSS selector.

    ``original_text`` is the exact snippet being replaced — the renderer
    matches on this string to apply the edit safely.
    """

    section_id: str = Field(
        ...,
        description=(
            "References the ``PageSection.section_id`` being edited "
            "(e.g., 'hero_0', 'benefits_0')."
        ),
    )
    edit_type: EditType = Field(
        ...,
        description="Category of edit being applied.",
    )
    original_text: str = Field(
        ...,
        description=(
            "Exact text from the original page being replaced. "
            "Step 4 uses this for string matching in the DOM."
        ),
    )
    replacement_text: str = Field(
        ...,
        description="The new text that replaces ``original_text``.",
    )
    reasoning: str = Field(
        ...,
        description=(
            "Why this edit was made — what ad signal it aligns with "
            "and what page weakness it addresses."
        ),
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence that this edit improves ad–page alignment (0–1).",
    )


class EditPlan(BaseModel):
    """
    Structured edit plan generated by the Edit Agent LLM chain.

    Contains an ordered list of ``SectionEdit`` objects plus metadata.
    Consumed by Step 4 (Guardrails + Renderer) to apply edits to the DOM.
    """

    # ── Edits ───────────────────────────────────────────────────────────

    edits: list[SectionEdit] = Field(
        default_factory=list,
        description="Ordered list of section-level text replacements.",
    )

    # ── Strategy ────────────────────────────────────────────────────────

    overall_strategy: str = Field(
        ...,
        description=(
            "One-paragraph explanation of the personalization approach — "
            "what was changed and why."
        ),
    )
    tone_alignment: str = Field(
        ...,
        description=(
            "How the edits align the page's tone with the ad's tone and "
            "target audience."
        ),
    )

    # ── Metadata ────────────────────────────────────────────────────────

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall confidence in the edit plan (0–1).",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description=(
            "Caveats, risks, or issues — e.g., sections that could not "
            "be improved without inventing claims."
        ),
    )
